CREATE TABLE IF NOT EXISTS nomnom(
NAME TEXT,
NEIGHBOURHOOD TEXT,
CUISINE TEXT,
REVIEW REAL,
PRICE TEXT,
HEALTH TEXT
);

INSERT INTO nomnom(NAME, NEIGHBOURHOOD, CUISINE, REVIEW, PRICE, HEALTH)VALUES
('SAM','BROOKLYN','STEAK',4.4,'$$$$','A'),
('JOW','MIDTOWN','KOREAN',3.5,'$$','A'),
('JORDAN','MIDTOWN','PIZZA',4.0,'$$$','B'),
('ANDREW','QUEENS','CHINESE',3.9,'$','A'),
('IMAN','DOWNTOWN','AMERICAN',4.6,'$$$',''),
('TRISTAN','CHINATOWN','CHINESE',3.0,'$$',''),
('DIRTY CANDY','UPTOWN','ITALIAN',4.9,'$$','B'),
('DI FARA PIZZA','BROOKLYN','PIZZA',3.8,'$$$','A'),
('GOLDEN UNICORN','UPTOWN','ITALIAN',3.8,'$$','A');

SELECT * FROM nomnom;

SELECT DISTINCT NEIGHBOURHOOD FROM nomnom;

SELECT DISTINCT CUISINE FROM nomnom;

SELECT * FROM nomnom WHERE CUISINE = 'CHINESE';

SELECT * FROM nomnom WHERE REVIEW >= 4;

SELECT * FROM nomnom WHERE CUISINE = 'ITALIAN' AND PRICE = '$$$';

SELECT * FROM nomnom WHERE NAME LIKE '%CANDY%';

SELECT * FROM nomnom 
WHERE NEIGHBOURHOOD IN ('MIDTOWN', 'DOWNTOWN', 'CHINATOWN');

SELECT * FROM nomnom ORDER BY REVIEW DESC LIMIT 4 ;